name: custom-check
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make install
        env: 
          CI: true
      - run: make lint
      - run: make prepare
      - name: Test & publish code coverage
      # Publish code coverage on Code Climate
      # https://github.com/paambaati/codeclimate-action
        uses: paambaati/codeclimate-action@v4.0.0
        # Add Code Climate secret key
        env:
          NODE_ENV: ${{ secrets.NODE_ENV }}
          ROLLBAR_TOKEN: ${{ secrets.ROLLBAR_TOKEN }}
          SESSION_KEY: ${{ secrets.SESSION_KEY }}
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true